### ISSUE TITLE
the reason behind letting word embedding not being updated

### ISSUE THREAD

**Issue by un-lock-me** [behnamsabeti/LSTM_autoencoder#2]
Again thanks for sharing your code. 
I am curious to know if you did not get a good result by letting the embedding getting trained during training?

**Comment by behnamsabeti** [comment]
The code is trying to show you how to use an auto-encoder for feature extraction. But you can certainly try any modification. I think fine tuning the embeddings is a good option where you have a prediction task and you want the embeddings to capture some information about the task in hand. However, in this case we want to encode and decode each sample so fine tuning the embeddings does not seem to be a valid strategy. Again this is my idea and I would like to know the results if you tried it. Thanks for your interest.
