### ISSUE TITLE
error

### ISSUE THREAD

**Issue by un-lock-me** [behnamsabeti/LSTM_autoencoder#3]
Is there any specific version of lexicon which supports `sentiment weight`?

```
Traceback (most recent call last):
  File "/home/sgnbx/Downloads/projects/LSTM_autoencoder-master/lstm_ae.py", line 135, in <module>
    sample_seq_weights[index_sentence,index_word] = lexicon.get_word_sentiment_weight(temp_words[index_word])
AttributeError: module 'lexicon' has no attribute 'get_word_sentiment_weight'
```
I faced with this Error while running the code.

**Comment by behnamsabeti** [comment]
Thanks for pointing out this issue. The lexicon part of the code is to train the auto-encoder with more attention to sentiment words. This part was in my research and I've forgotten to remove it for the blog post. I commented out this line and now you should be able to run the code.
